BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20# pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE-150
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE+40

REFRESH_RATE=60

BACK_GROUND_COLOR_GREEN=(10,196,44)
#soldier
SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part
#flag
FLAG_ROWS = 3
FLAG_COLS = 4
#mine
MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

